2024-08-22 07:59:03,775 INFO    StreamThr :85275 [internal.py:wandb_internal():85] W&B internal server running at pid: 85275, started at: 2024-08-22 07:59:03.774415
2024-08-22 07:59:03,776 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status
2024-08-22 07:59:03,786 INFO    WriterThread:85275 [datastore.py:open_for_write():87] open: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/run-swfaq5hh.wandb
2024-08-22 07:59:03,787 DEBUG   SenderThread:85275 [sender.py:send():391] send: header
2024-08-22 07:59:03,829 DEBUG   SenderThread:85275 [sender.py:send():391] send: run
2024-08-22 07:59:04,569 INFO    SenderThread:85275 [dir_watcher.py:__init__():211] watching files in: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files
2024-08-22 07:59:04,570 INFO    SenderThread:85275 [sender.py:_start_run_threads():1200] run started: swfaq5hh with start time 1724306343.775208
2024-08-22 07:59:04,582 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: check_version
2024-08-22 07:59:04,582 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: check_version
2024-08-22 07:59:06,913 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: run_start
2024-08-22 07:59:06,921 DEBUG   HandlerThread:85275 [system_info.py:__init__():26] System info init
2024-08-22 07:59:06,921 DEBUG   HandlerThread:85275 [system_info.py:__init__():41] System info init done
2024-08-22 07:59:06,921 INFO    HandlerThread:85275 [system_monitor.py:start():194] Starting system monitor
2024-08-22 07:59:06,921 INFO    SystemMonitor:85275 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-08-22 07:59:06,921 INFO    HandlerThread:85275 [system_monitor.py:probe():214] Collecting system info
2024-08-22 07:59:06,924 INFO    SystemMonitor:85275 [interfaces.py:start():188] Started cpu monitoring
2024-08-22 07:59:06,927 INFO    SystemMonitor:85275 [interfaces.py:start():188] Started disk monitoring
2024-08-22 07:59:06,927 INFO    SystemMonitor:85275 [interfaces.py:start():188] Started gpuapple monitoring
2024-08-22 07:59:06,930 INFO    SystemMonitor:85275 [interfaces.py:start():188] Started memory monitoring
2024-08-22 07:59:06,931 INFO    SystemMonitor:85275 [interfaces.py:start():188] Started network monitoring
2024-08-22 07:59:07,099 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:07,172 ERROR   HandlerThread:85275 [gpu_apple.py:probe():176] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:07,172 DEBUG   HandlerThread:85275 [system_info.py:probe():152] Probing system
2024-08-22 07:59:07,176 DEBUG   HandlerThread:85275 [system_info.py:_probe_git():137] Probing git
2024-08-22 07:59:07,204 DEBUG   HandlerThread:85275 [system_info.py:_probe_git():145] Probing git done
2024-08-22 07:59:07,204 DEBUG   HandlerThread:85275 [system_info.py:probe():200] Probing system done
2024-08-22 07:59:07,204 DEBUG   HandlerThread:85275 [system_monitor.py:probe():223] {'os': 'macOS-14.5-arm64-arm-64bit', 'python': '3.11.5', 'heartbeatAt': '2024-08-22T05:59:07.172513', 'startedAt': '2024-08-22T05:59:03.770277', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/jackbmontgomery/deep-predictive-active-inference.git', 'commit': '1691130b1ebb3fdf0ed5eb01f8f3d39f97f44a07'}, 'email': 'jackbmontgomery2001@gmail.com', 'root': '/Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference', 'host': 'Jacks-MacBook-Pro-2.local', 'username': 'jackmontgomery', 'executable': '/Users/jackmontgomery/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 212.87998962402344}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 16.0}}
2024-08-22 07:59:07,204 INFO    HandlerThread:85275 [system_monitor.py:probe():224] Finished collecting system info
2024-08-22 07:59:07,204 INFO    HandlerThread:85275 [system_monitor.py:probe():227] Publishing system info
2024-08-22 07:59:07,204 DEBUG   HandlerThread:85275 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-08-22 07:59:07,581 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/conda-environment.yaml
2024-08-22 07:59:09,208 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:10,763 DEBUG   HandlerThread:85275 [system_info.py:_save_conda():224] Saving conda packages done
2024-08-22 07:59:10,764 INFO    HandlerThread:85275 [system_monitor.py:probe():229] Finished publishing system info
2024-08-22 07:59:10,765 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:10,765 DEBUG   SenderThread:85275 [sender.py:send():391] send: files
2024-08-22 07:59:10,765 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-metadata.json with policy now
2024-08-22 07:59:10,962 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: python_packages
2024-08-22 07:59:10,962 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 07:59:10,962 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: python_packages
2024-08-22 07:59:10,963 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:10,963 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 07:59:11,309 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:11,367 DEBUG   SenderThread:85275 [sender.py:send():391] send: telemetry
2024-08-22 07:59:11,596 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/conda-environment.yaml
2024-08-22 07:59:11,596 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-metadata.json
2024-08-22 07:59:11,596 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/requirements.txt
2024-08-22 07:59:11,620 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,620 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,621 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,621 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,621 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,621 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,621 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,621 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,622 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,622 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,622 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,622 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,622 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,623 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,623 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,623 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,623 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,623 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,623 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,623 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,623 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,623 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,624 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,624 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,624 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,624 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,624 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,625 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,626 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,626 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,626 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,626 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,626 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,626 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,626 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,627 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,628 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,628 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,628 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,628 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,628 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,628 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,629 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,629 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,630 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,630 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,630 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,630 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,631 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,631 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,631 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,631 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,631 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,631 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,632 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,632 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,632 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,632 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,632 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,633 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,633 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,633 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,633 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,633 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,633 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,633 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,634 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,634 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,634 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,634 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,634 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,635 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,635 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,635 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,635 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,636 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,636 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,636 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,636 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,636 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,637 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,637 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,637 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,637 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,638 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,638 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,638 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,638 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,638 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,638 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,639 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,639 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,639 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,639 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,639 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,640 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,640 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,640 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,640 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,640 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,641 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,641 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,641 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,641 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,641 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,641 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,641 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,642 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,642 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,642 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,642 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,643 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,643 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,643 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,643 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,644 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:11,644 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:11,644 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:11,644 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:11,968 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:12,055 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:12,056 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:12,056 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:12,056 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:12,067 INFO    wandb-upload_0:85275 [upload_job.py:push():130] Uploaded file /var/folders/qc/h4k546bs6j9bl76bcjwyw5cw0000gn/T/tmp80vkw__8wandb/z0wt5up1-wandb-metadata.json
2024-08-22 07:59:12,227 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:12,227 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:12,227 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:12,228 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:12,445 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:12,446 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:12,446 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:12,446 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:12,601 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:12,601 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:12,652 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:12,652 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:12,652 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:12,652 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:12,800 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:12,800 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:12,800 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:12,801 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:12,973 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:13,047 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:13,047 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:13,047 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:13,048 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:13,288 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:13,288 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:13,288 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:13,288 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:13,418 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:13,601 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:13,704 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:13,704 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:13,704 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:13,704 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:13,974 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:13,980 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:13,980 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:13,980 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:13,980 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:13,981 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:14,606 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:14,607 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:14,800 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:14,800 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:14,800 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:14,800 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:14,976 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:15,521 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:15,612 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:15,979 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:16,617 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:16,984 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:17,622 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:17,987 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:18,667 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:18,668 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:18,668 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:18,669 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:18,989 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:19,631 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:19,632 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:19,674 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:19,731 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:19,990 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:20,994 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:21,835 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:21,999 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:22,999 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:23,944 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:24,001 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:24,732 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:24,732 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:24,732 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:24,732 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:24,733 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:25,003 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:25,659 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:25,659 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:25,968 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 07:59:25,968 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 07:59:26,007 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:26,057 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:27,010 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:28,011 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:28,164 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:29,015 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:30,018 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:30,273 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:30,294 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:30,607 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:30,607 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:30,607 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:30,608 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:30,678 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:31,019 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:31,683 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:32,024 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:32,380 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:33,029 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:34,034 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:34,495 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:35,039 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:35,984 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:36,044 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:36,600 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:36,707 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/config.yaml
2024-08-22 07:59:37,049 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:37,097 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:37,097 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:37,097 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:37,098 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:37,713 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:37,713 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:38,053 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:38,701 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:39,058 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:40,060 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:40,819 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:40,972 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 07:59:40,972 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 07:59:41,062 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:41,358 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:42,067 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:43,066 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:43,070 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:44,073 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:45,077 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:45,182 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:46,082 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:46,296 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:46,296 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:46,296 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:46,297 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:46,743 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:47,088 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:47,299 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:47,302 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:47,748 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:48,090 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:48,846 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:48,847 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:48,847 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:48,847 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:49,091 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:49,403 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:49,758 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:49,758 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:50,096 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:51,101 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:51,509 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:52,103 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:52,629 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:52,629 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:52,630 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:52,630 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:52,630 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:52,767 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:53,108 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:53,615 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:53,773 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:54,115 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:55,119 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:55,731 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:55,973 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 07:59:55,973 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 07:59:56,122 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:56,964 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:56,965 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:56,965 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:56,965 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:57,128 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:57,791 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:57,791 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:57,839 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 07:59:57,971 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 07:59:58,133 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:59,093 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 07:59:59,093 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 07:59:59,093 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 07:59:59,094 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 07:59:59,138 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 07:59:59,800 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 07:59:59,800 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 07:59:59,943 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:00,139 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:01,141 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:02,051 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:02,143 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:02,292 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:02,292 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:02,292 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:02,292 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:02,812 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:03,148 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:03,298 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 08:00:03,817 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:04,149 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:04,156 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:05,154 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:05,998 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:05,998 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:05,999 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:05,999 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:06,161 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:06,261 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:06,829 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:06,935 DEBUG   SystemMonitor:85275 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-08-22 08:00:06,936 DEBUG   SenderThread:85275 [sender.py:send():391] send: telemetry
2024-08-22 08:00:06,936 DEBUG   SenderThread:85275 [sender.py:send():391] send: stats
2024-08-22 08:00:07,163 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:07,834 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:08,167 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:08,368 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:08,397 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:08,399 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 08:00:08,762 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:08,762 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:08,763 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:08,836 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:08,836 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/config.yaml
2024-08-22 08:00:09,168 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:09,841 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:10,170 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:10,496 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:10,978 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 08:00:10,978 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 08:00:11,171 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:11,560 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:11,560 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:11,560 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:11,560 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:11,852 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:12,176 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:12,608 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:13,178 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:13,858 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:14,181 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:14,365 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:14,365 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 08:00:14,365 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:14,365 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:14,366 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:14,717 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:14,863 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:15,186 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:15,868 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:16,189 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:16,828 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:17,194 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:17,711 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:17,711 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:17,711 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:17,712 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:17,874 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:18,195 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:18,938 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:19,200 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:19,721 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 08:00:19,885 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:20,203 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:21,052 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:21,206 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:21,312 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:21,312 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:21,312 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:21,313 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:21,895 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:21,895 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:22,211 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:23,161 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:23,213 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:24,218 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:24,859 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:24,860 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: status_report
2024-08-22 08:00:24,860 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:24,860 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:24,861 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:24,905 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:25,220 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:25,265 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:25,906 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
2024-08-22 08:00:25,980 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: stop_status
2024-08-22 08:00:25,981 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: stop_status
2024-08-22 08:00:26,225 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:27,230 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:27,372 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:28,235 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:28,320 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: partial_history
2024-08-22 08:00:28,321 DEBUG   SenderThread:85275 [sender.py:send():391] send: history
2024-08-22 08:00:28,321 DEBUG   SenderThread:85275 [sender.py:send_request():418] send_request: summary_record
2024-08-22 08:00:28,321 INFO    SenderThread:85275 [sender.py:_save_file():1466] saving file wandb-summary.json with policy end
2024-08-22 08:00:28,921 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/wandb-summary.json
2024-08-22 08:00:29,240 DEBUG   HandlerThread:85275 [handler.py:handle_request():158] handle_request: internal_messages
2024-08-22 08:00:29,479 ERROR   gpuapple  :85275 [gpu_apple.py:sample():110] GPU stats error: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jackmontgomery/anaconda3/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jackmontgomery/anaconda3/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-08-22 08:00:29,924 INFO    Thread-12 :85275 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/jackmontgomery/Desktop/UCT/Research_Project/deep-predictive-active-inference/wandb/run-20240822_075903-swfaq5hh/files/output.log
